### ISSUE TITLE
Поднимаем Selenoid

### ISSUE THREAD

**Issue by eroshenkoam** [eroshenkoam/docker-example#3]
Добавляем в `docker-compose.yaml`
```
version: '3.4'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "${PWD}/init/selenoid:/etc/selenoid"
      - "${PWD}/work/selenoid/video:/opt/selenoid/video"
      - "${PWD}/work/selenoid/logs:/opt/selenoid/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=work/selenoid/video
    command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
    network_mode: bridge
```

Создаем конфиг браузеров `init/selenoid/browsers.json`
```
{
  "chrome": {
    "default": "75.0",
    "versions": {
      "75.0": {
        "env" : ["LANG=ru_RU.UTF-8", "LANGUAGE=ru:en", "LC_ALL=ru_RU.UTF-8", "TZ=Europe/Moscow"],
        "image": "selenoid/vnc:chrome_75.0",
        "tmpfs": {"/tmp": "size=512m"},
        "hosts": ["x01.aidata.io:127.0.0.1"],
        "port": "4444"
      },
      "76.0": {
        "env": ["LANG=ru_RU.UTF-8", "LANGUAGE=ru:en", "LC_ALL=ru_RU.UTF-8", "TZ=Europe/Moscow"],
        "image": "selenoid/vnc:chrome_76.0",
        "tmpfs": {"/tmp": "size=512m"},
        "hosts": ["x01.aidata.io:127.0.0.1"],
        "port": "4444"
      }
    }
  }
}
```

Заменяем на remote webdriver: 
```
    @BeforeEach
    public void initDriver() throws IOException {
        final String url = "http://192.168.90.245:4444/wd/hub";
        WebDriver driver = new RemoteWebDriver(new URL(url), DesiredCapabilities.chrome());
        driver.manage().window().setSize(new Dimension(1920,1024));
        WebDriverRunner.setWebDriver(driver);
    }

    @AfterEach
    public void stopDriver() {
        Optional.ofNullable(WebDriverRunner.getWebDriver()).ifPresent(WebDriver::quit);
    }


```
