### ISSUE TITLE
Поднимаем Jenkins

### ISSUE THREAD

**Issue by eroshenkoam** [eroshenkoam/docker-example#4]
Добавляем service в `docker-compose.yaml`

```
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - ${PWD}/work/jenkins:/var/jenkins_home
    ports:
      - 8000:8080
    network_mode: bridge
```

Запускаем наши тесты командой `./gradlew clean test --no-daemon`
