### ISSUE TITLE
Поднимаем Jira

### ISSUE THREAD

**Issue by eroshenkoam** [eroshenkoam/docker-example#5]
Добавляем в  `docker-compose.yaml`
```
  jira:
    image: atlassian/jira-software
    volumes:
    - "${PWD}/work/jira:/var/atlassian/application-data/jira"
    ports:
      - "9999:8080"
    network_mode: bridge
```
